# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/shu/NewGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/shu/NewGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shu/NewGame/CMakeFiles /home/shu/NewGame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/shu/NewGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named mugGame.exe

# Build rule for target.
mugGame.exe: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 mugGame.exe
.PHONY : mugGame.exe

# fast build rule for target.
mugGame.exe/fast:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/build
.PHONY : mugGame.exe/fast

AddInventory.o: AddInventory.cpp.o

.PHONY : AddInventory.o

# target to build an object file
AddInventory.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/AddInventory.cpp.o
.PHONY : AddInventory.cpp.o

AddInventory.i: AddInventory.cpp.i

.PHONY : AddInventory.i

# target to preprocess a source file
AddInventory.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/AddInventory.cpp.i
.PHONY : AddInventory.cpp.i

AddInventory.s: AddInventory.cpp.s

.PHONY : AddInventory.s

# target to generate assembly for a file
AddInventory.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/AddInventory.cpp.s
.PHONY : AddInventory.cpp.s

ArcherBattle.o: ArcherBattle.cpp.o

.PHONY : ArcherBattle.o

# target to build an object file
ArcherBattle.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherBattle.cpp.o
.PHONY : ArcherBattle.cpp.o

ArcherBattle.i: ArcherBattle.cpp.i

.PHONY : ArcherBattle.i

# target to preprocess a source file
ArcherBattle.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherBattle.cpp.i
.PHONY : ArcherBattle.cpp.i

ArcherBattle.s: ArcherBattle.cpp.s

.PHONY : ArcherBattle.s

# target to generate assembly for a file
ArcherBattle.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherBattle.cpp.s
.PHONY : ArcherBattle.cpp.s

ArcherSkill.o: ArcherSkill.cpp.o

.PHONY : ArcherSkill.o

# target to build an object file
ArcherSkill.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherSkill.cpp.o
.PHONY : ArcherSkill.cpp.o

ArcherSkill.i: ArcherSkill.cpp.i

.PHONY : ArcherSkill.i

# target to preprocess a source file
ArcherSkill.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherSkill.cpp.i
.PHONY : ArcherSkill.cpp.i

ArcherSkill.s: ArcherSkill.cpp.s

.PHONY : ArcherSkill.s

# target to generate assembly for a file
ArcherSkill.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/ArcherSkill.cpp.s
.PHONY : ArcherSkill.cpp.s

BerserkerBattle.o: BerserkerBattle.cpp.o

.PHONY : BerserkerBattle.o

# target to build an object file
BerserkerBattle.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerBattle.cpp.o
.PHONY : BerserkerBattle.cpp.o

BerserkerBattle.i: BerserkerBattle.cpp.i

.PHONY : BerserkerBattle.i

# target to preprocess a source file
BerserkerBattle.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerBattle.cpp.i
.PHONY : BerserkerBattle.cpp.i

BerserkerBattle.s: BerserkerBattle.cpp.s

.PHONY : BerserkerBattle.s

# target to generate assembly for a file
BerserkerBattle.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerBattle.cpp.s
.PHONY : BerserkerBattle.cpp.s

BerserkerSkill.o: BerserkerSkill.cpp.o

.PHONY : BerserkerSkill.o

# target to build an object file
BerserkerSkill.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerSkill.cpp.o
.PHONY : BerserkerSkill.cpp.o

BerserkerSkill.i: BerserkerSkill.cpp.i

.PHONY : BerserkerSkill.i

# target to preprocess a source file
BerserkerSkill.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerSkill.cpp.i
.PHONY : BerserkerSkill.cpp.i

BerserkerSkill.s: BerserkerSkill.cpp.s

.PHONY : BerserkerSkill.s

# target to generate assembly for a file
BerserkerSkill.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/BerserkerSkill.cpp.s
.PHONY : BerserkerSkill.cpp.s

CasterBattle.o: CasterBattle.cpp.o

.PHONY : CasterBattle.o

# target to build an object file
CasterBattle.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterBattle.cpp.o
.PHONY : CasterBattle.cpp.o

CasterBattle.i: CasterBattle.cpp.i

.PHONY : CasterBattle.i

# target to preprocess a source file
CasterBattle.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterBattle.cpp.i
.PHONY : CasterBattle.cpp.i

CasterBattle.s: CasterBattle.cpp.s

.PHONY : CasterBattle.s

# target to generate assembly for a file
CasterBattle.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterBattle.cpp.s
.PHONY : CasterBattle.cpp.s

CasterSkill.o: CasterSkill.cpp.o

.PHONY : CasterSkill.o

# target to build an object file
CasterSkill.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterSkill.cpp.o
.PHONY : CasterSkill.cpp.o

CasterSkill.i: CasterSkill.cpp.i

.PHONY : CasterSkill.i

# target to preprocess a source file
CasterSkill.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterSkill.cpp.i
.PHONY : CasterSkill.cpp.i

CasterSkill.s: CasterSkill.cpp.s

.PHONY : CasterSkill.s

# target to generate assembly for a file
CasterSkill.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/CasterSkill.cpp.s
.PHONY : CasterSkill.cpp.s

HpPotion.o: HpPotion.cpp.o

.PHONY : HpPotion.o

# target to build an object file
HpPotion.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/HpPotion.cpp.o
.PHONY : HpPotion.cpp.o

HpPotion.i: HpPotion.cpp.i

.PHONY : HpPotion.i

# target to preprocess a source file
HpPotion.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/HpPotion.cpp.i
.PHONY : HpPotion.cpp.i

HpPotion.s: HpPotion.cpp.s

.PHONY : HpPotion.s

# target to generate assembly for a file
HpPotion.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/HpPotion.cpp.s
.PHONY : HpPotion.cpp.s

IntEnergy.o: IntEnergy.cpp.o

.PHONY : IntEnergy.o

# target to build an object file
IntEnergy.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/IntEnergy.cpp.o
.PHONY : IntEnergy.cpp.o

IntEnergy.i: IntEnergy.cpp.i

.PHONY : IntEnergy.i

# target to preprocess a source file
IntEnergy.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/IntEnergy.cpp.i
.PHONY : IntEnergy.cpp.i

IntEnergy.s: IntEnergy.cpp.s

.PHONY : IntEnergy.s

# target to generate assembly for a file
IntEnergy.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/IntEnergy.cpp.s
.PHONY : IntEnergy.cpp.s

MakeAccount.o: MakeAccount.cpp.o

.PHONY : MakeAccount.o

# target to build an object file
MakeAccount.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeAccount.cpp.o
.PHONY : MakeAccount.cpp.o

MakeAccount.i: MakeAccount.cpp.i

.PHONY : MakeAccount.i

# target to preprocess a source file
MakeAccount.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeAccount.cpp.i
.PHONY : MakeAccount.cpp.i

MakeAccount.s: MakeAccount.cpp.s

.PHONY : MakeAccount.s

# target to generate assembly for a file
MakeAccount.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeAccount.cpp.s
.PHONY : MakeAccount.cpp.s

MakeArcher.o: MakeArcher.cpp.o

.PHONY : MakeArcher.o

# target to build an object file
MakeArcher.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeArcher.cpp.o
.PHONY : MakeArcher.cpp.o

MakeArcher.i: MakeArcher.cpp.i

.PHONY : MakeArcher.i

# target to preprocess a source file
MakeArcher.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeArcher.cpp.i
.PHONY : MakeArcher.cpp.i

MakeArcher.s: MakeArcher.cpp.s

.PHONY : MakeArcher.s

# target to generate assembly for a file
MakeArcher.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeArcher.cpp.s
.PHONY : MakeArcher.cpp.s

MakeBerserker.o: MakeBerserker.cpp.o

.PHONY : MakeBerserker.o

# target to build an object file
MakeBerserker.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeBerserker.cpp.o
.PHONY : MakeBerserker.cpp.o

MakeBerserker.i: MakeBerserker.cpp.i

.PHONY : MakeBerserker.i

# target to preprocess a source file
MakeBerserker.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeBerserker.cpp.i
.PHONY : MakeBerserker.cpp.i

MakeBerserker.s: MakeBerserker.cpp.s

.PHONY : MakeBerserker.s

# target to generate assembly for a file
MakeBerserker.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeBerserker.cpp.s
.PHONY : MakeBerserker.cpp.s

MakeCaster.o: MakeCaster.cpp.o

.PHONY : MakeCaster.o

# target to build an object file
MakeCaster.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeCaster.cpp.o
.PHONY : MakeCaster.cpp.o

MakeCaster.i: MakeCaster.cpp.i

.PHONY : MakeCaster.i

# target to preprocess a source file
MakeCaster.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeCaster.cpp.i
.PHONY : MakeCaster.cpp.i

MakeCaster.s: MakeCaster.cpp.s

.PHONY : MakeCaster.s

# target to generate assembly for a file
MakeCaster.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeCaster.cpp.s
.PHONY : MakeCaster.cpp.s

MakeMonster.o: MakeMonster.cpp.o

.PHONY : MakeMonster.o

# target to build an object file
MakeMonster.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeMonster.cpp.o
.PHONY : MakeMonster.cpp.o

MakeMonster.i: MakeMonster.cpp.i

.PHONY : MakeMonster.i

# target to preprocess a source file
MakeMonster.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeMonster.cpp.i
.PHONY : MakeMonster.cpp.i

MakeMonster.s: MakeMonster.cpp.s

.PHONY : MakeMonster.s

# target to generate assembly for a file
MakeMonster.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeMonster.cpp.s
.PHONY : MakeMonster.cpp.s

MakePotion.o: MakePotion.cpp.o

.PHONY : MakePotion.o

# target to build an object file
MakePotion.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakePotion.cpp.o
.PHONY : MakePotion.cpp.o

MakePotion.i: MakePotion.cpp.i

.PHONY : MakePotion.i

# target to preprocess a source file
MakePotion.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakePotion.cpp.i
.PHONY : MakePotion.cpp.i

MakePotion.s: MakePotion.cpp.s

.PHONY : MakePotion.s

# target to generate assembly for a file
MakePotion.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakePotion.cpp.s
.PHONY : MakePotion.cpp.s

MakeSaber.o: MakeSaber.cpp.o

.PHONY : MakeSaber.o

# target to build an object file
MakeSaber.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeSaber.cpp.o
.PHONY : MakeSaber.cpp.o

MakeSaber.i: MakeSaber.cpp.i

.PHONY : MakeSaber.i

# target to preprocess a source file
MakeSaber.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeSaber.cpp.i
.PHONY : MakeSaber.cpp.i

MakeSaber.s: MakeSaber.cpp.s

.PHONY : MakeSaber.s

# target to generate assembly for a file
MakeSaber.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MakeSaber.cpp.s
.PHONY : MakeSaber.cpp.s

MpPotion.o: MpPotion.cpp.o

.PHONY : MpPotion.o

# target to build an object file
MpPotion.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MpPotion.cpp.o
.PHONY : MpPotion.cpp.o

MpPotion.i: MpPotion.cpp.i

.PHONY : MpPotion.i

# target to preprocess a source file
MpPotion.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MpPotion.cpp.i
.PHONY : MpPotion.cpp.i

MpPotion.s: MpPotion.cpp.s

.PHONY : MpPotion.s

# target to generate assembly for a file
MpPotion.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/MpPotion.cpp.s
.PHONY : MpPotion.cpp.s

SaberBattle.o: SaberBattle.cpp.o

.PHONY : SaberBattle.o

# target to build an object file
SaberBattle.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberBattle.cpp.o
.PHONY : SaberBattle.cpp.o

SaberBattle.i: SaberBattle.cpp.i

.PHONY : SaberBattle.i

# target to preprocess a source file
SaberBattle.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberBattle.cpp.i
.PHONY : SaberBattle.cpp.i

SaberBattle.s: SaberBattle.cpp.s

.PHONY : SaberBattle.s

# target to generate assembly for a file
SaberBattle.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberBattle.cpp.s
.PHONY : SaberBattle.cpp.s

SaberSkill.o: SaberSkill.cpp.o

.PHONY : SaberSkill.o

# target to build an object file
SaberSkill.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberSkill.cpp.o
.PHONY : SaberSkill.cpp.o

SaberSkill.i: SaberSkill.cpp.i

.PHONY : SaberSkill.i

# target to preprocess a source file
SaberSkill.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberSkill.cpp.i
.PHONY : SaberSkill.cpp.i

SaberSkill.s: SaberSkill.cpp.s

.PHONY : SaberSkill.s

# target to generate assembly for a file
SaberSkill.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/SaberSkill.cpp.s
.PHONY : SaberSkill.cpp.s

WeaponStatus.o: WeaponStatus.cpp.o

.PHONY : WeaponStatus.o

# target to build an object file
WeaponStatus.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/WeaponStatus.cpp.o
.PHONY : WeaponStatus.cpp.o

WeaponStatus.i: WeaponStatus.cpp.i

.PHONY : WeaponStatus.i

# target to preprocess a source file
WeaponStatus.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/WeaponStatus.cpp.i
.PHONY : WeaponStatus.cpp.i

WeaponStatus.s: WeaponStatus.cpp.s

.PHONY : WeaponStatus.s

# target to generate assembly for a file
WeaponStatus.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/WeaponStatus.cpp.s
.PHONY : WeaponStatus.cpp.s

main.o: main.cpp.o

.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i

.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s

.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) -f CMakeFiles/mugGame.exe.dir/build.make CMakeFiles/mugGame.exe.dir/main.cpp.s
.PHONY : main.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... mugGame.exe"
	@echo "... AddInventory.o"
	@echo "... AddInventory.i"
	@echo "... AddInventory.s"
	@echo "... ArcherBattle.o"
	@echo "... ArcherBattle.i"
	@echo "... ArcherBattle.s"
	@echo "... ArcherSkill.o"
	@echo "... ArcherSkill.i"
	@echo "... ArcherSkill.s"
	@echo "... BerserkerBattle.o"
	@echo "... BerserkerBattle.i"
	@echo "... BerserkerBattle.s"
	@echo "... BerserkerSkill.o"
	@echo "... BerserkerSkill.i"
	@echo "... BerserkerSkill.s"
	@echo "... CasterBattle.o"
	@echo "... CasterBattle.i"
	@echo "... CasterBattle.s"
	@echo "... CasterSkill.o"
	@echo "... CasterSkill.i"
	@echo "... CasterSkill.s"
	@echo "... HpPotion.o"
	@echo "... HpPotion.i"
	@echo "... HpPotion.s"
	@echo "... IntEnergy.o"
	@echo "... IntEnergy.i"
	@echo "... IntEnergy.s"
	@echo "... MakeAccount.o"
	@echo "... MakeAccount.i"
	@echo "... MakeAccount.s"
	@echo "... MakeArcher.o"
	@echo "... MakeArcher.i"
	@echo "... MakeArcher.s"
	@echo "... MakeBerserker.o"
	@echo "... MakeBerserker.i"
	@echo "... MakeBerserker.s"
	@echo "... MakeCaster.o"
	@echo "... MakeCaster.i"
	@echo "... MakeCaster.s"
	@echo "... MakeMonster.o"
	@echo "... MakeMonster.i"
	@echo "... MakeMonster.s"
	@echo "... MakePotion.o"
	@echo "... MakePotion.i"
	@echo "... MakePotion.s"
	@echo "... MakeSaber.o"
	@echo "... MakeSaber.i"
	@echo "... MakeSaber.s"
	@echo "... MpPotion.o"
	@echo "... MpPotion.i"
	@echo "... MpPotion.s"
	@echo "... SaberBattle.o"
	@echo "... SaberBattle.i"
	@echo "... SaberBattle.s"
	@echo "... SaberSkill.o"
	@echo "... SaberSkill.i"
	@echo "... SaberSkill.s"
	@echo "... WeaponStatus.o"
	@echo "... WeaponStatus.i"
	@echo "... WeaponStatus.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

